apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect-ui
spec:
  rules:
  - host: "ard-modeling-service.slac.stanford.edu"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: prefect-server
            port:
              number: 4200
