apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-server
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mlflow-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/controls: "true"
        io.kompose.service: mlflow-server
    spec:
      containers:
        - args:
            - bash
            - -c
            - pip install mlflow[auth] boto3 psycopg2-binary && mlflow server --serve-artifacts --host 0.0.0.0 --backend-store-uri postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@mlflow-db:5436/mlflowdb --default-artifact-root s3://mlflow-bucket/ --app-name basic-auth --workers 1
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: env
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: env
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_REGION
                  name: env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: env
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: env
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_USER
                  name: env
            - name: MINIO_SITE_REGION
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SITE_REGION
                  name: env
            - name: MLFLOW_FLASK_SERVER_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MLFLOW_FLASK_SERVER_SECRET_KEY
                  name: env
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  key: MLFLOW_S3_ENDPOINT_URL
                  name: env
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            # - name: MLFLOW_AUTH_CONFIG_PATH
            #   valueFrom:
            #     configMapKeyRef:
            #       key: MLFLOW_AUTH_CONFIG_PATH
            #       name: env
          image: python:3.9.15-slim
          name: mlflow-server
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mlflow
              name: mlflow-server-claim0
            # - mountPath: /cfgs/basic_auth.ini
            #   name: mlflow-db-config
      restartPolicy: Always
      volumes:
        - name: mlflow-server-claim0
          persistentVolumeClaim:
            claimName: mlflow-server-claim0
        # - name: mlflow-db-config
        #   secret:
        #     secretName: mlflow-db-config
status: {}
